### ISSUE TITLE
which versions

### ISSUE THREAD

**Issue by blueforesticarus** [nobitagit/polymer-slidenav#1]
install with bower results in the fallowing message

polymer#0.3.6 depends on platform#^0.3.0 which resolved to platform#0.3.6
    polymer-slidenav depends on platform#~1.3.0 which resolved to platform#1.3.0
Resort to using platform#~1.3.0 which resolved to platform#1.3.0
Code incompatibilities may occur.

and surely enough the menus don't work

which versions are you using for platform and polymir

**Comment by nobitagit** [comment]
Installed via Bower right now on a fresh folder, mounted a quick demo and got no errors in the terminal and the menu works for me.

Have you tried this on an existing project or tested on a new one?

**Comment by blueforesticarus** [comment]
using:
── platform#0.3.6
── polymer#0.3.6

i was able to get the slide menu working
